# Generated by Django 5.1.5 on 2025-02-03 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keuangan', '0003_transaksi'),
    ]

    operations = [
        migrations.AddField(
            model_name='anggaran',
            name='pengeluaran',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
